logging:
  file: ''
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
    root: INFO
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  ssl:
    key-store: classpath:6741330_api.798ipartstore.com.pfx
    key-store-password: 28za5xyD
    key-store-type: PKCS12
    enable: true
  port: 443
#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    password: lin5241!
#    url: jdbc:mysql://gz-cynosdbmysql-grp-j76qo6c9.sql.tencentcdb.com:29523/go_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: woshilijianWoAichiTudou!
    url: jdbc:mysql://rm-2zeibb8575f8bc1c4.mysql.rds.aliyuncs.com:3306/go_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: jiangechitudou
