spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  profiles:
    active: dev

weChat:
  appId: wx138cfb45ada6bdcc
  appSecret: 9290921f40da4788eca292719f3ee34d
  grantType: authorization_code
  v2:
    appId: wx71dfe9d7cf33f2d2
    appSecret: 1cdde2c9a698724f95d041d0dcfc0940
    grantType: authorization_code

server:
  ssl:
    key-store: classpath:6741330_api.798ipartstore.com.pfx
    key-store-password: 28za5xyD
    key-store-type: PKCS12
    enable: true
