logging:
  file: ''
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
    root: INFO
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
server:
  port: 443