spring:
  profiles:
    active: dev

weChat:
  appId: wx138cfb45ada6bdcc
  appSecret: 9290921f40da4788eca292719f3ee34d
  grantType: authorization_code

#1server:
#1  ssl:
#1    key-store: classpath:api.beartcenter.com.pfx
#1    key-store-password: 7Oq59KeY
#1    key-store-type: PKCS12
#1
