spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  profiles:
    active: release

weChat:
  appId: wx138cfb45ada6bdcc
  appSecret: 9290921f40da4788eca292719f3ee34d
  grantType: authorization_code
  v2:
    appId: wx71dfe9d7cf33f2d2
    appSecret: 1cdde2c9a698724f95d041d0dcfc0940
    grantType: authorization_code

server:
  ssl:
    key-store: classpath:fullchain_and_key.jks
    key-store-password: 123456
    key-store-type: JKS
    enable: true
