logging:
  file: ''
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
    root: INFO
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  ssl:
    key-store: classpath:api_798ipartstore.jks
    key-store-password: 123456
    key-store-type: JKS
    enable: true
  port: 443
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: yE@N#@9r2fk6
    url: jdbc:mysql://rm-2ze52i18m9k5m4s3j.mysql.rds.aliyuncs.com:3306/go_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: admin798
